name: Run Unit Tests API

on: [push, pull_request]

jobs:
  run-unit-tests:
    name: Run Unit Tests API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 9.6.0

      - uses: actions/setup-node@v3
        with:
          node-version: 24
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm prisma generate

      - run: pnpm run test
        env:
          NODE_ENV: test
          DATABASE_URL: "env.DATABASE_URL"
          PORT: 3333
          SMTP_USER: "env.SMTP_USER"
          SMTP_PASS: "env.SMTP_PASS"
         